server:
  port: 8201

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.90.186:8761/eureka/
#
#  instance:
#    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
#    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）

spring:
  application:
    name: vehicle-service
  zipkin:
    base-url: http://192.168.90.186:9411
#  datasource:
#    url: jdbc:mysql://192.168.80.109:3306/oauth?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#  #ddl策略
#    jpa:
#      hibernate:
#        ddl-auto: update
#测试数据库地址
  datasource:
    #抓取SQL运行时的参数值
    # url: jdbc:log4jdbc:mysql://192.168.80.109:3306/vehicle?udockseUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://192.168.80.109:3306/vehicle?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    #抓取SQL运行时的参数值
    #driver-class-name: net.sf.log4jdbc.DriverSpy
    driver-class-name: com.mysql.jdbc.Driver
#ddl策略
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
  redis:
      host: 192.168.80.208
      port: 6379
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 20
        max-wait: 60000
      database: 0 #默认是索引为的0的数据库
      # Redis服务器连接密码（默认为空）
      password: 123456

logging:
  level:
    org.springframework.security: info
    org.springframework: info
    com.jy.mapper: debug
  config: classpath:log4j2-dev.yml
jwt:
  header: Authorization
  secret: mySecret
  access_token:
    expiration: 604800
  refresh_token:
    expiration: 604800
  tokenHead: "Bearer "
